// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJkZ7IR5jG39a_0bURavcknfyDqVCJ2oI',
    appId: '1:200517894761:web:1646f52eadc37477bcd8f8',
    messagingSenderId: '200517894761',
    projectId: 'employeeform-8c6dc',
    authDomain: 'employeeform-8c6dc.firebaseapp.com',
    storageBucket: 'employeeform-8c6dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1P-EaUFv7YJIPt4VBQlfzV2LNSM-MKX0',
    appId: '1:200517894761:android:9f182bb787406c13bcd8f8',
    messagingSenderId: '200517894761',
    projectId: 'employeeform-8c6dc',
    storageBucket: 'employeeform-8c6dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJC4ZIPGQ2HxIJz8CVnNwxzKzSTC5kSHk',
    appId: '1:200517894761:ios:460df83151fdb18dbcd8f8',
    messagingSenderId: '200517894761',
    projectId: 'employeeform-8c6dc',
    storageBucket: 'employeeform-8c6dc.firebasestorage.app',
    iosBundleId: 'com.example.employeeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJC4ZIPGQ2HxIJz8CVnNwxzKzSTC5kSHk',
    appId: '1:200517894761:ios:460df83151fdb18dbcd8f8',
    messagingSenderId: '200517894761',
    projectId: 'employeeform-8c6dc',
    storageBucket: 'employeeform-8c6dc.firebasestorage.app',
    iosBundleId: 'com.example.employeeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJkZ7IR5jG39a_0bURavcknfyDqVCJ2oI',
    appId: '1:200517894761:web:db2d6a0dc38e31ccbcd8f8',
    messagingSenderId: '200517894761',
    projectId: 'employeeform-8c6dc',
    authDomain: 'employeeform-8c6dc.firebaseapp.com',
    storageBucket: 'employeeform-8c6dc.firebasestorage.app',
  );
}
